import type { CSSProperties } from "react";

export const s = {
  card: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    overflow: "hidden",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  head: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 16px",
    cursor: "pointer",
    background: "none",
    border: "none",
    width: "100%",
    textAlign: "left",
  } satisfies CSSProperties,
  headIcon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  headTitle: { fontSize: 14, fontWeight: 600, color: "var(--text-primary)", flex: 1 } satisfies CSSProperties,
  chevron: (open: boolean): CSSProperties => ({
    color: "var(--text-muted)",
    transform: open ? "rotate(180deg)" : "none",
    transition: "transform .15s",
  }),
  body: { borderTop: "1px solid var(--border)", padding: 16, display: "flex", flexDirection: "column", gap: 4 } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "6px 0",
    fontSize: 13,
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  rowLabel: { color: "var(--text-secondary)" } satisfies CSSProperties,
  rowRight: { display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 1 } satisfies CSSProperties,
  rowTokens: { color: "var(--text-muted)", fontSize: 12 } satisfies CSSProperties,
  rowUsd: { color: "var(--text-primary)", fontSize: 13, fontWeight: 500 } satisfies CSSProperties,
  noPricing: { color: "var(--text-muted)", fontSize: 11.5, fontStyle: "italic" } satisfies CSSProperties,
  totalRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "8px 0 0",
    fontSize: 13.5,
    fontWeight: 700,
  } satisfies CSSProperties,
  chip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "4px 10px",
    borderRadius: 6,
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--text-secondary)",
    background: "var(--bg-hover)",
    border: "1px solid var(--border)",
  } satisfies CSSProperties,
};
