/* Co-located styles for the Export Wizard (SPEC-05 T10). Pixel layout/colour
   tokens are HOW, not spec'd (spec "Screens & states" intro) — this mirrors the
   design source (`screen_export.jsx`) closely without chasing exact pixels. */
import type { CSSProperties } from "react";

export const s = {
  stepBody: { padding: 20 } satisfies CSSProperties,
  stepperWrap: {
    padding: "18px 20px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  footerRow: { display: "flex", alignItems: "center", width: "100%" } satisfies CSSProperties,

  // ---- Target step ----
  targetGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 12,
  } satisfies CSSProperties,
  targetCard: (selected: boolean, disabled: boolean): CSSProperties => ({
    textAlign: "left",
    padding: 16,
    borderRadius: 10,
    cursor: disabled ? "not-allowed" : "pointer",
    background: "var(--bg-surface)",
    borderWidth: 1.5,
    borderStyle: "solid",
    borderColor: selected ? "var(--accent)" : "var(--border)",
    opacity: disabled ? 0.6 : 1,
  }),
  targetCardHead: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  targetIconBox: (selected: boolean): CSSProperties => ({
    width: 34,
    height: 34,
    borderRadius: 8,
    background: "var(--bg-elevated)",
    display: "grid",
    placeItems: "center",
    color: selected ? "var(--accent)" : "var(--text-secondary)",
  }),
  targetName: { fontSize: 14, fontWeight: 600 } satisfies CSSProperties,
  targetDesc: { fontSize: 12, color: "var(--text-muted)", marginTop: 8 } satisfies CSSProperties,
  badgeRight: { marginLeft: "auto" } satisfies CSSProperties,
  repoField: { marginTop: 20 } satisfies CSSProperties,

  // ---- Preview step ----
  previewGrid: {
    display: "grid",
    gridTemplateColumns: "260px 1fr",
    gap: 0,
    height: 340,
    border: "1px solid var(--border)",
    borderRadius: 9,
    overflow: "hidden",
  } satisfies CSSProperties,
  fileTreePane: {
    borderRight: "1px solid var(--border)",
    padding: 10,
    background: "var(--bg-surface)",
    overflow: "auto",
  } satisfies CSSProperties,
  fileTreeLabel: {
    fontSize: 10.5,
    fontWeight: 700,
    color: "var(--text-muted)",
    letterSpacing: "0.05em",
    padding: "2px 8px 8px",
  } satisfies CSSProperties,
  fileRow: (active: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 7,
    padding: "5px 8px",
    borderRadius: 5,
    cursor: "pointer",
    fontSize: 12,
    background: active ? "var(--accent-bg)" : "transparent",
    border: "none",
    width: "100%",
    textAlign: "left",
  }),
  fileContentPane: { display: "flex", flexDirection: "column", minWidth: 0 } satisfies CSSProperties,
  fileContentHeader: {
    padding: "8px 12px",
    borderBottom: "1px solid var(--border)",
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  fileContentPath: { fontSize: 12, flex: 1 } satisfies CSSProperties,
  fileContentBody: {
    margin: 0,
    padding: 14,
    fontSize: 11.5,
    lineHeight: 1.6,
    overflow: "auto",
    flex: 1,
    color: "var(--text-primary)",
    background: "var(--code-bg)",
  } satisfies CSSProperties,
  previewMuted: { padding: "8px", fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,

  // ---- Configure step ----
  configureWrap: { maxWidth: 600 } satisfies CSSProperties,
  chipsRow: { display: "flex", flexWrap: "wrap", gap: 7 } satisfies CSSProperties,
  radioColumn: { display: "flex", flexDirection: "column", gap: 9 } satisfies CSSProperties,
  radioRow: {
    display: "flex",
    alignItems: "center",
    gap: 9,
    fontSize: 13,
    color: "var(--text-secondary)",
    cursor: "pointer",
  } satisfies CSSProperties,
  infoBox: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "11px 13px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  infoIcon: { color: "var(--text-muted)", flexShrink: 0, marginTop: 1 } satisfies CSSProperties,
  infoText: { fontSize: 12.5, color: "var(--text-secondary)", lineHeight: 1.5 } satisfies CSSProperties,
  infoTitle: { fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,

  // ---- Install step ----
  installWrap: { maxWidth: 600, display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  installPrimaryCard: {
    width: "100%",
    textAlign: "left",
    padding: 18,
    borderRadius: 10,
    border: "1.5px solid var(--accent)",
    background: "var(--accent-bg)",
    cursor: "pointer",
  } satisfies CSSProperties,
  installCardHead: { display: "flex", alignItems: "center", gap: 10, marginBottom: 8 } satisfies CSSProperties,
  installCardTitle: { fontSize: 14, fontWeight: 700 } satisfies CSSProperties,
  installCardBody: { fontSize: 12.5, color: "var(--text-secondary)", lineHeight: 1.5, margin: 0 } satisfies CSSProperties,
  installSecondaryCard: {
    width: "100%",
    textAlign: "left",
    padding: 16,
    borderRadius: 10,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-surface)",
    cursor: "pointer",
  } satisfies CSSProperties,
  installSecondaryHead: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  installSecondaryTitle: { fontSize: 13.5, fontWeight: 600 } satisfies CSSProperties,
  installSecondaryHint: { marginLeft: "auto", fontSize: 11.5, color: "var(--text-muted)" } satisfies CSSProperties,
  prSuccessBox: {
    padding: "10px 13px",
    borderRadius: 8,
    border: "1px solid var(--ok, var(--border))",
    background: "var(--bg-surface)",
    fontSize: 12.5,
  } satisfies CSSProperties,
  prLink: { color: "var(--accent-text)", wordBreak: "break-all" } satisfies CSSProperties,
  errorBox: {
    padding: "11px 13px",
    borderRadius: 8,
    border: "1px solid var(--crit)",
    background: "var(--crit-bg)",
  } satisfies CSSProperties,
  errorTitle: { fontSize: 13, fontWeight: 700, color: "var(--crit)" } satisfies CSSProperties,
  errorBody: { fontSize: 12.5, color: "var(--text-secondary)", marginTop: 4, lineHeight: 1.5 } satisfies CSSProperties,
  docsFooter: { fontSize: 11.5, color: "var(--text-muted)", marginTop: 6, textAlign: "center" } satisfies CSSProperties,
  docsLink: { color: "var(--accent-text)" } satisfies CSSProperties,
} as const;
