import type { CSSProperties } from "react";

/** Inline styles for ConventionCard (dark theme via CSS vars). */
export const st = {
  card: (accent: string, dim?: boolean): CSSProperties => ({
    display: "flex",
    gap: 16,
    alignItems: "flex-start",
    justifyContent: "space-between",
    padding: 18,
    borderRadius: 12,
    border: "1px solid var(--border)",
    borderLeft: `3px solid ${accent}`,
    background: "var(--bg-elevated)",
    opacity: dim ? 0.6 : 1,
    transition: "opacity .2s ease",
  }),
  body: { flex: 1, minWidth: 0 } as CSSProperties,
  header: { display: "flex", flexDirection: "column", gap: 8, marginBottom: 12 } as CSSProperties,
  rule: {
    margin: 0,
    fontSize: 15,
    fontWeight: 600,
    fontStyle: "italic",
    color: "var(--text-primary)",
    lineHeight: 1.4,
  } as CSSProperties,
  editFields: { display: "flex", flexDirection: "column", gap: 8 } as CSSProperties,
  evidence: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-base, #0c0d10)",
    overflow: "hidden",
    marginBottom: 14,
  } as CSSProperties,
  evidenceHead: {
    padding: "8px 12px",
    borderBottom: "1px solid var(--border)",
    fontSize: 12.5,
  } as CSSProperties,
  evidenceLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    color: "var(--text-secondary)",
    textDecoration: "none",
  } as CSSProperties,
  evidencePath: { color: "var(--text-secondary)" } as CSSProperties,
  snippet: {
    margin: 0,
    padding: "10px 12px",
    fontSize: 12.5,
    lineHeight: 1.6,
    color: "var(--text-primary)",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  } as CSSProperties,
  confidenceRow: { display: "flex", alignItems: "center", gap: 12 } as CSSProperties,
  confidenceLabel: { fontSize: 12.5, color: "var(--text-tertiary, #8a8f98)" } as CSSProperties,
  confidenceBar: { flex: 1, maxWidth: 240 } as CSSProperties,
  confidencePct: {
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--text-secondary)",
    minWidth: 36,
    textAlign: "right",
  } as CSSProperties,
  actions: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    flexShrink: 0,
    minWidth: 120,
  } as CSSProperties,
};
