import type {
  CiExport,
  CiInstallation,
  CiRun,
  CiRunStatus,
  RepoRef,
  RunSummary,
} from '@devdigest/shared';
import type { Container } from '../../platform/container.js';
import { ExternalServiceError, NotFoundError } from '../../platform/errors.js';
import { assembleBundle, type BundleAgent, type BundleSkill, type PostAs, type TriggerType } from './bundle.js';
import { DEFAULT_WORKFLOW_VERSION } from './constants.js';
import {
  computeConfigHash,
  parseRepoRef,
  resolveAgentSlug,
  toBundleAgent,
  toCiInstallationDto,
} from './helpers.js';
import { CiRepository, type CiRunJoined, type ListCiRunsFilters } from './repository.js';
import { reconcileCiRuns, type ReconcileOptions, type ReconcileSummary } from './reconcile.js';
import { zipFiles } from './zip.js';

// Re-exported so T7's routes.ts can import everything CI-related from
// `service.ts` alone (mirrors `bundle.ts` re-exporting `manifest.ts`/`workflow.ts`'s errors).
export { UnresolvedSkillError, InvalidManifestError } from './bundle.js';
export type { ListCiRunsFilters } from './repository.js';
export type { ReconcileOptions, ReconcileSummary } from './reconcile.js';

const CI_PR_BODY =
  'Adds a DevDigest CI review workflow for this agent. Generated by DevDigest — ' +
  'see `.devdigest/` for the agent manifest + skills and `.github/workflows/` for the ' +
  'generated workflow. No secret is embedded; the workflow reads `secrets.OPENROUTER_API_KEY` ' +
  'and the CI-provided `GITHUB_TOKEN` at run time.\n\n' +
  "This PR's own first CI run will show a notice (not a failure) since " +
  '`.devdigest/runner.mjs` is not yet on the base branch — the review activates ' +
  'on the next pull request after this one merges.';

export interface InstallInput {
  workspaceId: string;
  agentId: string;
  /** "owner/name" — validated via `parseRepoRef` (throws `ValidationError` on a bad shape). */
  repo: string;
  /** Base branch to fork `devdigest/ci` from when it doesn't exist yet. Defaults to `'main'`. */
  base?: string;
  triggers?: TriggerType[];
  postAs?: PostAs;
}

export interface PreviewInput {
  workspaceId: string;
  agentId: string;
  /** "owner/name" — validated via `parseRepoRef` (throws `ValidationError` on a bad shape). */
  repo: string;
  triggers?: TriggerType[];
  postAs?: PostAs;
}

export interface ExportZipInput {
  workspaceId: string;
  agentId: string;
  /**
   * Optional — the wizard's "Copy files as a zip" step (T10's `useExportZip`)
   * calls this with just an agent id, no repo: the generated file set (unlike
   * `install`'s commit/PR) never varies by repo, so `repo` here is used ONLY
   * to recover an already-installed `workflow_version` for byte-parity with
   * `install`/`preview` when the caller happens to know it.
   */
  repo?: string;
  triggers?: TriggerType[];
  postAs?: PostAs;
}

/**
 * T6 — install (commit+PR, idempotent), reconcile/ingest, drift, and the
 * read-shaping (installations/CI runs/agent runs) T7's routes call.
 */
export class CiService {
  private repo: CiRepository;

  constructor(private container: Container) {
    this.repo = new CiRepository(container.db);
  }

  /**
   * Export an agent to CI: assemble the bundle (AC-2/12/13/14), commit it
   * atomically onto `devdigest/ci` (AC-9), and reuse-or-open a PR (AC-17).
   * Re-exporting an already-installed agent+repo reuses the same
   * installation row, branch, and open PR — bumping `workflow_version` and
   * `installed_config_hash` in place (AC-17/41) — and never creates a
   * duplicate installation or a second PR.
   *
   * On `openPullRequest` failure this throws `ExternalServiceError` (502,
   * `external_service_error`) — the ONE typed error T7's route maps to a
   * "PR failed — use the zip instead" response (AC-11). No DB row is written
   * in that case: `commitFiles` is atomic (the branch it leaves behind is a
   * complete, valid tree, never a half-written one), and the installation
   * insert/bump only runs AFTER a PR URL is in hand.
   */
  async install(input: InstallInput): Promise<CiExport> {
    const agent = await this.container.agentsRepo.getById(input.workspaceId, input.agentId);
    if (!agent) throw new NotFoundError(`Agent "${input.agentId}" not found`);

    const repoRef = parseRepoRef(input.repo);
    const normalizedRepo = `${repoRef.owner}/${repoRef.name}`;

    const linkedSkillRows = await this.container.agentsRepo.linkedSkills(input.agentId);
    // Include DISABLED links as-is (not filtered out) — `assembleBundle` is
    // what enforces AC-12 by throwing `UnresolvedSkillError` when it sees one.
    const linkedSkills: BundleSkill[] = linkedSkillRows.map((l) => ({
      name: l.skill.name,
      body: l.skill.body,
      enabled: l.skill.enabled,
    }));

    const existing = await this.repo.findInstallation(input.agentId, normalizedRepo);
    const nextWorkflowVersion = existing ? existing.workflowVersion + 1 : DEFAULT_WORKFLOW_VERSION;

    const existingSlugs = await this.otherAgentSlugs(input.workspaceId, input.agentId);
    const bundleAgent = toBundleAgent(agent);

    // AC-12/14 both enforced inside assembleBundle, BEFORE any GitHub call —
    // a thrown error here has zero side effects (no commit, no DB write).
    const bundle = assembleBundle(bundleAgent, {
      linkedSkills,
      existingSlugs,
      workflowVersion: nextWorkflowVersion,
      triggers: input.triggers,
      postAs: input.postAs,
    });

    const github = await this.container.github();
    const base = input.base ?? 'main';

    // Atomic — creates/advances the branch with the full file set in one
    // commit (AC-9). Never partial: either every file lands, or none does.
    await github.commitFiles(repoRef, {
      branch: 'devdigest/ci',
      base,
      message: 'Add DevDigest CI review',
      files: bundle.files,
    });

    let prUrl = (await github.findOpenPr(repoRef, 'devdigest/ci'))?.url ?? null;
    if (!prUrl) {
      try {
        const opened = await github.openPullRequest(repoRef, {
          title: 'Add DevDigest CI review',
          head: 'devdigest/ci',
          base,
          body: CI_PR_BODY,
        });
        prUrl = opened.url;
      } catch (err) {
        // No installation row is written past this point (AC-11) — the
        // branch commit above is real but complete-in-itself, not a partial
        // export; the route/client fall back to offering the zip download.
        throw new ExternalServiceError(
          `Could not open the CI pull request for "${normalizedRepo}" — the files were committed to the "devdigest/ci" branch, but the pull request could not be opened.`,
          { cause: err instanceof Error ? err.message : String(err) },
        );
      }
    }

    const configHash = computeConfigHash(bundleAgent, linkedSkills.map((s) => s.name), bundle.slug);
    const row = existing
      ? await this.repo.bumpInstallation(existing.id, {
          workflowVersion: nextWorkflowVersion,
          installedConfigHash: configHash,
        })
      : await this.repo.insertInstallation({
          agentId: input.agentId,
          repo: normalizedRepo,
          targetType: 'gha',
          workflowVersion: nextWorkflowVersion,
          installedConfigHash: configHash,
        });
    if (!row) throw new NotFoundError(`CI installation for agent "${input.agentId}" could not be found`);

    const latest = await this.repo.latestRunForInstallation(row.id);
    const installation = toCiInstallationDto(
      row,
      (latest?.status as CiRunStatus | null) ?? null,
      latest?.ranAt ?? null,
      false, // just (re-)installed at the current hash — never drifted immediately after
    );

    return { installation, files: bundle.files, pr_url: prUrl };
  }

  /**
   * Preview step (AC-2/3/4/5) — resolves the SAME bundle `install` would
   * produce (identical skill-resolution/manifest-validation gates, AC-12/14)
   * but makes NO GitHub write: no commit, no PR, no DB row. `installation` is
   * the real (drift-checked) installation DTO when this agent+repo is
   * already installed, or a lightweight, never-persisted stub otherwise — so
   * the wizard always has something to render without implying an install
   * happened. `pr_url` best-effort reflects an existing open
   * `devdigest/ci` PR for this repo (degrades to `null`, never throws, when
   * no GitHub client is configured — preview must stay usable before a token
   * is set up).
   */
  async preview(input: PreviewInput): Promise<CiExport> {
    const { bundleAgent, linkedSkills, existingSlugs } = await this.resolveAgentAndSkills(
      input.workspaceId,
      input.agentId,
    );

    const repoRef = parseRepoRef(input.repo);
    const normalizedRepo = `${repoRef.owner}/${repoRef.name}`;
    const existing = await this.repo.findInstallation(input.agentId, normalizedRepo);
    const nextWorkflowVersion = existing ? existing.workflowVersion + 1 : DEFAULT_WORKFLOW_VERSION;

    // AC-12/14 surfaced identically to install — thrown before any GitHub
    // call, so a preview can never leak a half-resolved bundle either.
    const bundle = assembleBundle(bundleAgent, {
      linkedSkills,
      existingSlugs,
      workflowVersion: nextWorkflowVersion,
      triggers: input.triggers,
      postAs: input.postAs,
    });

    const prUrl = await this.findOpenPrSafely(repoRef);

    let installation: CiInstallation;
    if (existing) {
      const latest = await this.repo.latestRunForInstallation(existing.id);
      const configHash = computeConfigHash(bundleAgent, linkedSkills.map((s) => s.name), bundle.slug);
      installation = toCiInstallationDto(
        existing,
        (latest?.status as CiRunStatus | null) ?? null,
        latest?.ranAt ?? null,
        existing.installedConfigHash !== configHash,
      );
    } else {
      // Nothing installed yet — a stub DTO (never persisted, never read back)
      // so the Preview step still has an `installation` to render.
      installation = {
        id: 'preview',
        agent_id: input.agentId,
        repo: normalizedRepo,
        target_type: 'gha',
        target: 'gha',
        installed_at: new Date().toISOString(),
        workflow_version: nextWorkflowVersion,
        status: null,
        last_run_at: null,
        update_available: false,
      };
    }

    return { installation, files: bundle.files, pr_url: prUrl };
  }

  /**
   * The "Copy files as a zip" degraded install path (AC-10/11) — the SAME
   * bundle generator, zipped via `zip.ts`, with no GitHub call at all (a zip
   * download never needs one). Skill/manifest gates (AC-12/14) still apply.
   */
  async exportZip(input: ExportZipInput): Promise<Uint8Array> {
    const { bundleAgent, linkedSkills, existingSlugs } = await this.resolveAgentAndSkills(
      input.workspaceId,
      input.agentId,
    );

    let nextWorkflowVersion: number = DEFAULT_WORKFLOW_VERSION;
    if (input.repo) {
      const repoRef = parseRepoRef(input.repo);
      const normalizedRepo = `${repoRef.owner}/${repoRef.name}`;
      const existing = await this.repo.findInstallation(input.agentId, normalizedRepo);
      if (existing) nextWorkflowVersion = existing.workflowVersion + 1;
    }

    const bundle = assembleBundle(bundleAgent, {
      linkedSkills,
      existingSlugs,
      workflowVersion: nextWorkflowVersion,
      triggers: input.triggers,
      postAs: input.postAs,
    });

    return zipFiles(bundle.files);
  }

  /**
   * This agent's CI installations, each enriched with the read-time-derived
   * `status`/`last_run_at` (from the latest `ci_runs` row, AC-39) and
   * `update_available` (AC-40: `installed_config_hash` vs the agent's
   * CURRENT config hash, recomputed the same way `install` computes it).
   */
  async listInstallations(workspaceId: string, agentId: string): Promise<CiInstallation[]> {
    const agent = await this.container.agentsRepo.getById(workspaceId, agentId);
    if (!agent) return [];
    const rows = await this.repo.listByAgent(agentId);
    if (rows.length === 0) return [];

    const linkedSkillRows = await this.container.agentsRepo.linkedSkills(agentId);
    const existingSlugs = await this.otherAgentSlugs(workspaceId, agentId);
    const slug = resolveAgentSlug(agent.name, existingSlugs);
    const currentHash = computeConfigHash(
      toBundleAgent(agent),
      linkedSkillRows.map((l) => l.skill.name),
      slug,
    );

    const result: CiInstallation[] = [];
    for (const row of rows) {
      const latest = await this.repo.latestRunForInstallation(row.id);
      const updateAvailable = row.installedConfigHash !== currentHash;
      result.push(
        toCiInstallationDto(
          row,
          (latest?.status as CiRunStatus | null) ?? null,
          latest?.ranAt ?? null,
          updateAvailable,
        ),
      );
    }
    return result;
  }

  /**
   * Ingested CI runs, scoped to `workspaceId` (AC-35/36). `findings_counts`
   * (per-severity) and `duration_s` are populated from the
   * `critical`/`warning`/`suggestion`/`duration_ms` columns migration `0021`
   * added to `ci_runs` — null only when reconcile never observed
   * severity/duration data for that run (e.g. a `failed`/`running` row with
   * no artifact).
   */
  async listCiRuns(workspaceId: string, filters: ListCiRunsFilters = {}): Promise<CiRun[]> {
    const rows = await this.repo.listCiRuns(workspaceId, filters);
    return rows.map(toCiRunDto);
  }

  /** Local + CI run history for one agent (AC-42), each row carrying `source`. */
  async listAgentRuns(workspaceId: string, agentId: string): Promise<RunSummary[]> {
    return this.repo.listAgentRuns(workspaceId, agentId);
  }

  /** On-demand reconcile (AC-30/31/32/33/34) — pulls Actions runs + artifacts into `ci_runs` + `agent_runs(source='ci')`. */
  async reconcile(opts?: ReconcileOptions): Promise<ReconcileSummary> {
    return reconcileCiRuns(this.container, opts);
  }

  /**
   * Slugs already taken by every OTHER agent in the workspace that has been
   * exported at least once — the `existingSlugs` input `assembleBundle`/
   * `resolveAgentSlug` need for AC-15/17 disambiguation. Built by replaying
   * `resolveAgentSlug` over each name in turn so two OTHER agents' names
   * that collide with each other are ALSO disambiguated consistently, not
   * just against the current agent.
   */
  private async otherAgentSlugs(workspaceId: string, excludeAgentId: string): Promise<Set<string>> {
    const names = await this.repo.otherExportedAgentNames(workspaceId, excludeAgentId);
    const taken = new Set<string>();
    for (const name of names) taken.add(resolveAgentSlug(name, taken));
    return taken;
  }

  /**
   * Shared agent+linked-skill resolution for `preview`/`exportZip` — the same
   * lookups `install` inlines at its own top (kept inline there rather than
   * refactored onto this helper, so `install`'s already-verified behavior
   * stays untouched). Throws `NotFoundError` for an unknown agent, exactly
   * like `install`.
   */
  private async resolveAgentAndSkills(
    workspaceId: string,
    agentId: string,
  ): Promise<{ bundleAgent: BundleAgent; linkedSkills: BundleSkill[]; existingSlugs: Set<string> }> {
    const agent = await this.container.agentsRepo.getById(workspaceId, agentId);
    if (!agent) throw new NotFoundError(`Agent "${agentId}" not found`);

    const linkedSkillRows = await this.container.agentsRepo.linkedSkills(agentId);
    // Include DISABLED links as-is — `assembleBundle` enforces AC-12 by
    // throwing `UnresolvedSkillError` when it sees one (mirrors `install`).
    const linkedSkills: BundleSkill[] = linkedSkillRows.map((l) => ({
      name: l.skill.name,
      body: l.skill.body,
      enabled: l.skill.enabled,
    }));

    const existingSlugs = await this.otherAgentSlugs(workspaceId, agentId);
    return { bundleAgent: toBundleAgent(agent), linkedSkills, existingSlugs };
  }

  /**
   * Best-effort `devdigest/ci` open-PR lookup for the Preview step. Never
   * throws: no GitHub client configured (no token yet) or a lookup failure
   * both degrade to `null` rather than blocking a read-only preview.
   */
  private async findOpenPrSafely(repoRef: RepoRef): Promise<string | null> {
    try {
      const github = await this.container.github();
      return (await github.findOpenPr(repoRef, 'devdigest/ci'))?.url ?? null;
    } catch {
      return null;
    }
  }
}

/** Map a joined `ci_runs` row to the public `CiRun` DTO — see `listCiRuns`'s doc comment for the known-null fields. */
function toCiRunDto(row: CiRunJoined): CiRun {
  // `findings_counts` is null only when reconcile never recorded any
  // per-severity data for this run (e.g. failed/running, no artifact) —
  // present (even all-zero) whenever at least one of the three columns is set.
  const findingsCounts =
    row.critical == null && row.warning == null && row.suggestion == null
      ? null
      : { critical: row.critical ?? 0, warning: row.warning ?? 0, suggestion: row.suggestion ?? 0 };

  return {
    id: row.id,
    ci_installation_id: row.ciInstallationId,
    pr_number: row.prNumber,
    pr_title: row.prTitle,
    ran_at: row.ranAt ? row.ranAt.toISOString() : null,
    status: (row.status as CiRunStatus | null) ?? null,
    findings_count: row.findingsCount,
    findings_counts: findingsCounts,
    cost_usd: row.costUsd,
    github_url: row.githubUrl,
    actions_run_id: row.actionsRunId,
    source: row.source,
    agent: row.agentName,
    duration_s: row.durationMs != null ? row.durationMs / 1000 : null,
  };
}
