import type { CiFile } from '@devdigest/shared';
import {
  ACTIONS_CHECKOUT_USES,
  DEFAULT_POST_AS,
  DEFAULT_TRIGGERS,
  RUNNER_FILE_PATH,
  workflowFilePath,
} from './constants.js';

export type PostAs = 'github_review' | 'pr_comment' | 'none';
export type TriggerType = 'opened' | 'synchronize' | 'reopened';

const VALID_TRIGGERS: readonly TriggerType[] = ['opened', 'synchronize', 'reopened'];

export interface WorkflowOptions {
  /** Keys the workflow's filename + the `--slug=` flag passed to the runner. */
  slug: string;
  /** "Post results as" (AC-7/19). Defaults to `github_review`. */
  postAs?: PostAs;
  /** Configured trigger types (AC-6). Defaults to `['opened', 'synchronize']`; invalid/duplicate entries are dropped. */
  triggers?: TriggerType[];
}

/**
 * Generate the exported GitHub Actions workflow. SECURITY-CRITICAL — do not
 * weaken any of the following without re-reading SPEC-05 AC-4/6/25/26/27/28/29:
 *
 * - `permissions:` is EXACTLY `contents: read` + `pull-requests: write`,
 *   nothing broader (AC-25).
 * - Triggers on `on.pull_request.types` = the configured triggers only (AC-6).
 * - The event is `pull_request` (never `pull_request_target`) — a fork PR's
 *   job then runs with a read-only, repo-secret-free token, so the runner's
 *   own skip-on-no-credentials path (AC-27) is what actually protects it,
 *   not just this trigger choice — but `pull_request_target` would defeat
 *   that protection entirely by handing forks the base repo's secrets (AC-28).
 * - The ONLY `uses:` step is first-party, SHA-pinned `actions/checkout` —
 *   fetching this commit so the committed `.devdigest/runner.mjs` is present
 *   on disk. The review logic ships fully inside that committed file, so no
 *   marketplace action and no `devdigest/…@v1`-style placeholder is ever
 *   emitted (AC-4/29).
 * - The run step checks `.devdigest/runner.mjs` exists before invoking it —
 *   the export PR that first commits that file is checked out at its own
 *   BASE sha (see below), which never has the file yet; this turns that
 *   built-in bootstrap gap into a clean `exit 0` notice instead of a crash.
 * - The API key is referenced ONLY via `${{ secrets.OPENROUTER_API_KEY }}`;
 *   `GITHUB_TOKEN` comes from the CI-provided `${{ github.token }}`. Neither
 *   value is ever embedded literally (AC-26).
 * - Every line is plain, commented YAML a maintainer can read top to bottom
 *   (AC-29) — no generated indirection, no external template.
 */
export function generateWorkflow(options: WorkflowOptions): string {
  const triggers = normalizeTriggers(options.triggers);
  const postAs = options.postAs ?? DEFAULT_POST_AS;
  const typesLine = triggers.join(', ');

  return `# Generated by DevDigest — every line below is safe to read and edit.
#
# Runs the DevDigest review agent "${options.slug}" against pull requests in
# this repository. The full review engine (grounding gate included) ships
# inside the committed .devdigest/runner.mjs — no external or marketplace
# action is used, and no secret ever reaches a pull request opened from a
# fork (the runner itself skips the review when no API key is available).
name: DevDigest Review (${options.slug})

on:
  pull_request:
    types: [${typesLine}]

# Least privilege: read the diff, post a review/comment on the PR. Nothing else.
permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      # First-party, SHA-pinned. Pinned to the PR's BASE commit, never the PR
      # head/merge commit — a \`pull_request\` event otherwise checks out the
      # merge commit, which includes the PR author's own edits to this very
      # runner file. Since the very next step executes that checked-out
      # runner.mjs with repo secrets, an unpinned checkout would let a PR that
      # edits .devdigest/runner.mjs run attacker-controlled code with
      # OPENROUTER_API_KEY (same-repo PR) or as outright RCE (fork PR) — a
      # lethal-trifecta hole. The runner fetches the PR diff to review via the
      # GitHub API (not from this checkout), so pinning to base.sha does not
      # change review behavior — it only guarantees the code that RUNS is
      # always the trusted base-branch copy, never the PR's.
      - name: Check out repository
        uses: ${ACTIONS_CHECKOUT_USES}
        with:
          ref: \${{ github.event.pull_request.base.sha }}

      # Runs the review engine bundled at .devdigest/runner.mjs — the same
      # engine (grounding gate included) that powers local reviews. Guarded on
      # the file's presence: the PR that FIRST commits ${RUNNER_FILE_PATH} is
      # checked out (above) at its own base sha, which never has that file
      # yet — this exits 0 with a notice instead of crashing on that one PR.
      - name: Run DevDigest review
        run: |
          if [ ! -f ${RUNNER_FILE_PATH} ]; then
            echo "::notice::${RUNNER_FILE_PATH} isn't on the base branch yet — expected for the PR that first adds it. The review activates once this PR merges."
            exit 0
          fi
          node ${RUNNER_FILE_PATH} --slug=${options.slug} --post-as=${postAs}
        env:
          # Repo secret, referenced only — never embedded in this file. Empty
          # on fork PRs, in which case the runner skips the review without
          # ever accessing the secret.
          OPENROUTER_API_KEY: \${{ secrets.OPENROUTER_API_KEY }}
          # CI-provided token, scoped by the permissions block above.
          GITHUB_TOKEN: \${{ github.token }}
`;
}

function normalizeTriggers(triggers: TriggerType[] | undefined): TriggerType[] {
  const input = triggers && triggers.length > 0 ? triggers : [...DEFAULT_TRIGGERS];
  const deduped = [...new Set(input)].filter((t): t is TriggerType => VALID_TRIGGERS.includes(t));
  return deduped.length > 0 ? deduped : [...DEFAULT_TRIGGERS];
}

/** The workflow as a committed `CiFile` at `.github/workflows/devdigest-review-<slug>.yml` (AC-2), always `editable: true` (AC-3). */
export function workflowFile(options: WorkflowOptions): CiFile {
  return {
    path: workflowFilePath(options.slug),
    contents: generateWorkflow(options),
    editable: true,
  };
}
