import type { CSSProperties } from "react";

export const s = {
  card: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    overflow: "hidden",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  head: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "12px 16px",
  } satisfies CSSProperties,
  headToggle: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flex: 1,
    minWidth: 0,
    background: "none",
    border: "none",
    padding: 0,
    cursor: "pointer",
    textAlign: "left",
  } satisfies CSSProperties,
  headIcon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  headTitle: {
    fontSize: 14,
    fontWeight: 600,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  headActions: { display: "flex", alignItems: "center", gap: 4, flexShrink: 0 } satisfies CSSProperties,
  chevronBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    background: "none",
    border: "none",
    padding: 4,
    cursor: "pointer",
  } satisfies CSSProperties,
  spinIcon: {
    color: "var(--text-muted)",
    animation: "ddspin 1s linear infinite",
  } satisfies CSSProperties,
  chevron: (open: boolean): CSSProperties => ({
    color: "var(--text-muted)",
    transform: open ? "rotate(180deg)" : "none",
    transition: "transform .15s",
  }),
  body: { borderTop: "1px solid var(--border)", padding: 16, display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  failureBanner: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    padding: "8px 12px",
    borderRadius: 6,
    background: "var(--warn-bg, #2e2205)",
    border: "1px solid var(--warn, #f59e0b)",
    color: "var(--text-primary)",
    fontSize: 13,
    lineHeight: 1.5,
  } satisfies CSSProperties,
  retryLink: {
    background: "none",
    border: "none",
    padding: 0,
    marginLeft: 4,
    color: "var(--accent-text, var(--accent))",
    textDecoration: "underline",
    cursor: "pointer",
    fontSize: 13,
  } satisfies CSSProperties,
  emptyBody: { color: "var(--text-muted)", fontSize: 13 } satisfies CSSProperties,
};
