import type { CSSProperties } from "react";
import { GRID } from "./constants";

/** Co-located styles for the CI Runs page (N13). */
export const s = {
  pageHeader: {
    padding: "24px 32px 10px",
    display: "flex",
    alignItems: "flex-end",
    gap: 16,
  } satisfies CSSProperties,
  pageTitle: { fontSize: 22, fontWeight: 700, letterSpacing: "-0.02em" } satisfies CSSProperties,
  pageSubtitle: { fontSize: 13, color: "var(--text-secondary)", marginTop: 3 } satisfies CSSProperties,
  headerActions: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 10,
  } satisfies CSSProperties,
  autoRefresh: {
    fontSize: 11.5,
    color: "var(--text-muted)",
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
  } satisfies CSSProperties,
  autoRefreshDot: {
    width: 6,
    height: 6,
    borderRadius: 99,
    background: "var(--ok)",
  } satisfies CSSProperties,
  filterBar: {
    display: "flex",
    gap: 8,
    padding: "12px 32px",
    flexWrap: "wrap",
  } satisfies CSSProperties,
  filterItem: { minWidth: 150 } satisfies CSSProperties,
  tableCard: {
    margin: "6px 32px 44px",
    border: "1px solid var(--border)",
    borderRadius: 10,
    overflow: "hidden",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  headRow: {
    display: "grid",
    gridTemplateColumns: GRID,
    gap: 12,
    padding: "10px 16px",
    background: "var(--bg-surface)",
    borderBottom: "1px solid var(--border)",
    fontSize: 10.5,
    fontWeight: 700,
    letterSpacing: "0.04em",
    color: "var(--text-muted)",
    textTransform: "uppercase",
  } satisfies CSSProperties,
  row: (last: boolean): CSSProperties => ({
    display: "grid",
    gridTemplateColumns: GRID,
    gap: 12,
    padding: "12px 16px",
    borderBottom: last ? "none" : "1px solid var(--border)",
    alignItems: "center",
    fontSize: 12.5,
  }),
  timestamp: { fontSize: 11, color: "var(--text-secondary)" } satisfies CSSProperties,
  prCell: { minWidth: 0 } satisfies CSSProperties,
  prNumber: { fontSize: 11, color: "var(--accent-text)" } satisfies CSSProperties,
  prTitle: {
    fontSize: 12.5,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    display: "inline-block",
    verticalAlign: "bottom",
    maxWidth: "85%",
  } satisfies CSSProperties,
  agentCell: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  duration: { fontSize: 12 } satisfies CSSProperties,
  cost: { fontSize: 12, color: "var(--text-secondary)" } satisfies CSSProperties,
  muted: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  loadingStack: {
    padding: 20,
    display: "flex",
    flexDirection: "column",
    gap: 14,
  } satisfies CSSProperties,
} as const;
