import type { CSSProperties } from "react";

export const s = {
  page: { padding: "24px 32px 44px", maxWidth: 1120, margin: "0 auto" } satisfies CSSProperties,
  stack: { display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
  advisory: {
    fontSize: 12.5,
    color: "var(--text-muted)",
    marginBottom: 20,
    display: "flex",
    alignItems: "center",
    gap: 6,
  } satisfies CSSProperties,
  body: { display: "flex", gap: 32, alignItems: "flex-start" } satisfies CSSProperties,
  main: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
  banner: (kind: "warn" | "crit"): CSSProperties => ({
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "10px 14px",
    borderRadius: 8,
    background: kind === "warn" ? "var(--warn-bg, #2e2205)" : "var(--crit-bg)",
    border: `1px solid ${kind === "warn" ? "var(--warn, #f59e0b)" : "var(--crit)"}`,
    fontSize: 13,
    color: "var(--text-primary)",
  }),
  bannerText: { flex: 1, lineHeight: 1.5 } satisfies CSSProperties,
  emptyCenter: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    padding: "60px 28px",
    gap: 10,
  } satisfies CSSProperties,
  emptyIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    display: "grid",
    placeItems: "center",
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    color: "var(--text-muted)",
    marginBottom: 6,
  } satisfies CSSProperties,
  emptyTitle: { fontSize: 16, fontWeight: 700, color: "var(--text-primary)" } satisfies CSSProperties,
  emptyBody: { fontSize: 14, color: "var(--text-secondary)", maxWidth: 440, lineHeight: 1.6 } satisfies CSSProperties,
  emptyError: {
    fontSize: 13,
    color: "var(--crit)",
    maxWidth: 440,
    lineHeight: 1.5,
    background: "var(--crit-bg)",
    border: "1px solid var(--crit)",
    borderRadius: 8,
    padding: "10px 14px",
  } satisfies CSSProperties,
  spinRow: { display: "flex", alignItems: "center", gap: 8, color: "var(--text-muted)", fontSize: 13 } satisfies CSSProperties,
  spin: { animation: "ddspin 1s linear infinite" } satisfies CSSProperties,
};
