import type { CSSProperties } from "react";

export const s = {
  // Page-level padding — AppFrame's <main> has none, so each page supplies its
  // own gutter (matches the Conventions/PR-list "24px 32px" convention).
  page: { padding: "24px 32px 44px", display: "flex", flexDirection: "column", height: "100%" } as CSSProperties,
  header: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
    marginBottom: 20,
    flexShrink: 0,
  } as CSSProperties,
  title: { margin: 0, fontSize: 24, fontWeight: 700, color: "var(--text-primary)" } as CSSProperties,
  subtitle: { margin: "6px 0 0", fontSize: 13.5, color: "var(--text-tertiary, #8a8f98)" } as CSSProperties,
  headerActions: { display: "flex", gap: 10, flexShrink: 0 } as CSSProperties,
  stack: { display: "flex", flexDirection: "column", gap: 14 } as CSSProperties,

  workspace: {
    display: "flex",
    gap: 20,
    flex: 1,
    minHeight: 0,
  } as CSSProperties,

  listPane: {
    width: 320,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    gap: 10,
    minHeight: 0,
  } as CSSProperties,
  list: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
    display: "flex",
    flexDirection: "column",
    gap: 4,
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: 6,
    background: "var(--bg-surface)",
  } as CSSProperties,
  noMatches: {
    padding: "20px 12px",
    fontSize: 13,
    color: "var(--text-muted)",
    textAlign: "center",
  } as CSSProperties,
  docRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "8px 10px",
    borderRadius: 6,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "transparent",
    background: "transparent",
    cursor: "pointer",
    textAlign: "left",
    color: "var(--text-primary)",
  } as CSSProperties,
  docRowActive: {
    background: "var(--bg-hover)",
    borderColor: "var(--border-strong)",
  } as CSSProperties,
  docPath: {
    flex: 1,
    fontSize: 12.5,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    minWidth: 0,
  } as CSSProperties,

  previewPane: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-surface)",
    overflow: "hidden",
  } as CSSProperties,
  previewHeader: {
    padding: "10px 16px",
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--text-secondary)",
    borderBottom: "1px solid var(--border)",
    flexShrink: 0,
  } as CSSProperties,
  previewContent: {
    margin: 0,
    padding: 16,
    fontSize: 13,
    lineHeight: 1.6,
    color: "var(--text-primary)",
    overflow: "auto",
    flex: 1,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  } as CSSProperties,
  previewCenter: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  } as CSSProperties,
};
