import type { CSSProperties } from "react";

export const s = {
  wrap: { maxWidth: 820 } as CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12, marginBottom: 6 } as CSSProperties,
  h2: { fontSize: 16, fontWeight: 700 } as CSSProperties,
  hint: { fontSize: 12.5, color: "var(--text-muted)", marginBottom: 14, lineHeight: 1.5 } as CSSProperties,
  repoPicker: { display: "flex", alignItems: "center", gap: 10, marginBottom: 14 } as CSSProperties,
  repoLabel: { fontSize: 13, fontWeight: 600, color: "var(--text-secondary)", flexShrink: 0 } as CSSProperties,
  filterRow: { display: "flex", alignItems: "center", gap: 12, marginBottom: 10 } as CSSProperties,
  countRow: { display: "flex", alignItems: "center", gap: 8, flexShrink: 0 } as CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 6 } as CSSProperties,
  row: (attached: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "9px 12px",
    borderRadius: 9,
    border: `1px solid ${attached ? "var(--accent)" : "var(--border)"}`,
    background: attached ? "var(--bg-hover)" : "var(--bg-elevated)",
    cursor: "grab",
  }),
  handle: { color: "var(--text-muted)", display: "inline-flex", cursor: "grab" } as CSSProperties,
  path: { flex: 1, fontSize: 13, color: "var(--text-primary)" } as CSSProperties,
  previewBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 5,
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "transparent",
    color: "var(--text-muted)",
    cursor: "pointer",
  } as CSSProperties,
  previewPane: {
    margin: "4px 0 0 38px",
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-hover)",
    fontSize: 12,
    lineHeight: 1.5,
    maxHeight: 220,
    overflow: "auto",
    whiteSpace: "pre-wrap",
  } as CSSProperties,
  untrustedNote: {
    display: "flex",
    gap: 10,
    padding: "10px 12px",
    marginTop: 14,
    borderRadius: 8,
    border: "1px solid var(--warn)",
    background: "var(--bg-hover)",
    fontSize: 12.5,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
  } as CSSProperties,
} as const;
